[profile.release]
panic = 'abort'
[package]
name = "folder_splitter_rust"
version = "0.1.0"
authors = ["nerioalfonso"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
zip = "0.5"
